name: PR Code Coverage and Build Check

on:
  pull_request:
    branches:
      - main # Target branch for pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Navigate to the React app directory
      - name: Navigate to Apparels Frontend
        working-directory: ./apperals-frontend
        run: echo "Changed working directory to apperals-frontend"

      # Step 3: Set up Node.js environment
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16 # Use the Node.js version your app requires

      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: ./apperals-frontend
        run: npm install

      # Step 5: Build the application
      - name: Build Application
        working-directory: ./apperals-frontend
        run: npm run build

      # Step 6: Run tests with coverage
      - name: Run Tests with Coverage
        working-directory: ./apperals-frontend
        run: npm test -- --coverage

      # Step 7: Upload coverage report to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # Optional: Path to your coverage report file (default is `coverage/**/coverage-final.json`)
          files: ./apperals-frontend/coverage/coverage-final.json
          # Optional: Set the name of your coverage report, if it's different
          name: coverage-report
          # Optional: Additional flags for Codecov (e.g., flags to enforce thresholds)
          flags: unittests

      # Step 8: Enforce Coverage Threshold (using Codecov API)
      - name: Enforce Coverage Threshold
        run: |
          # Fetch the coverage report from Codecov using the API with authentication
          COVERAGE=$(curl -s --header "Authorization: token ${{ secrets.CODECOV_API_TOKEN }}" \
          https://codecov.io/api/gh/NikhilRajivOke/ApparelsProject/commit/${{ github.sha }} | jq -r '.coverage')
          
          # Check if the coverage is fetched successfully
          if [ -z "$COVERAGE" ]; then
            echo "Error: Could not retrieve coverage data from Codecov"
            exit 1
          fi

          REQUIRED_COVERAGE=80
          echo "Current Coverage: $COVERAGE%"

          # Compare the current coverage with the required threshold
          if (( $(echo "$COVERAGE < $REQUIRED_COVERAGE" | bc -l) )); then
            echo "Coverage is below the required threshold of $REQUIRED_COVERAGE%"
            exit 1
          fi

      # Step 9: Upload coverage reports as artifacts (optional)
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: ./apperals-frontend/coverage/
