name: PR Code Coverage and Build Check

on:
  pull_request:
    branches:
      - main # Target branch for pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Navigate to the React app directory
      - name: Navigate to Apparels Frontend
        working-directory: ./apperals-frontend
        run: echo "Changed working directory to apperals-frontend"

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version your app requires

      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: ./apperals-frontend
        run: npm install

      # Step 5: Build the application
      - name: Build Application
        working-directory: ./apperals-frontend
        run: npm run build

      # Step 6: Run tests with coverage
      - name: Run Tests with Coverage
        working-directory: ./apperals-frontend
        run: npm test -- --coverage
        
      # Step 7: Validate coverage threshold (Branch coverage only)
      - name: Check Coverage Threshold
        working-directory: ./apperals-frontend
        run: |
          # Normalize paths (optional, but recommended)
          sed -i 's/\\/\//g' coverage/coverage-final.json 

          # Calculate the branch coverage 
          COVERAGE=$(jq '[ 
            .[] | 
            (
              ((.b // {}) | to_entries | map(.value) | add) / 
              (if ((.b // {}) | length) > 0 then ((.b // {}) | length) else 1 end) * 100 
            )
          ] | add / length' coverage/coverage-final.json)
          
          # Set the required coverage percentage
          REQUIRED_COVERAGE=80
          
          # Round the coverage to 2 decimal places for display
          COVERAGE_ROUNDED=$(echo "$COVERAGE" | awk '{printf "%.2f", $1}')
          
          echo "Current Branch Coverage: $COVERAGE_ROUNDED%"
          
          # Compare coverage with the required threshold
          if (( $(echo "$COVERAGE < $REQUIRED_COVERAGE" | bc -l) )); then
            echo "Branch coverage is below the required threshold of $REQUIRED_COVERAGE%"
            exit 1
          fi

      # Step 8: Upload coverage reports as artifacts (optional)
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: ./apparels-frontend/coverage/
