name: PR Code Coverage and Build Check

on:
  pull_request:
    branches:
      - main # Target branch for pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Navigate to the React app directory
      - name: Navigate to Apparels Frontend
        working-directory: ./apperals-frontend
        run: echo "Changed working directory to apparels-frontend"

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version your app requires

      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: ./apparels-frontend
        run: npm install

      # Step 5: Build the application
      - name: Build Application
        working-directory: ./apparels-frontend
        run: npm run build

      # Step 6: Run tests with coverage
      - name: Run Tests with Coverage
        working-directory: ./apparels-frontend
        run: npm test -- --coverage

      # Step 7: Validate coverage threshold
      - name: Check Coverage Threshold
        working-directory: ./apperals-frontend
        run: |
          COVERAGE=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          REQUIRED_COVERAGE=80 # Set your minimum required coverage percentage
          echo "Current Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < $REQUIRED_COVERAGE" | bc -l) )); then
            echo "Code coverage is below the required threshold of $REQUIRED_COVERAGE%"
            exit 1
          fi

      # Step 8: Upload coverage reports as artifacts (optional)
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: ./apparels-frontend/coverage/
