name: PR Code Coverage and Build Check

on:
  pull_request:
    branches:
      - main # Target branch for pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Navigate to the React app directory
      - name: Navigate to Apparels Frontend
        working-directory: ./apperals-frontend
        run: echo "Changed working directory to apperals-frontend"

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the Node.js version your app requires

      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: ./apperals-frontend
        run: npm install

      # Step 5: Build the application
      - name: Build Application
        working-directory: ./apperals-frontend
        run: npm run build

      # Step 6: Run tests with coverage
      - name: Run Tests with Coverage
        working-directory: ./apperals-frontend
        run: npm test -- --coverage

      # Step 7: Validate JSON (to catch structural errors)
      - name: Validate JSON
        working-directory: ./apperals-frontend
        run: |
          jq . coverage/coverage-final.json > /dev/null 2>&1
          if [[ $? -ne 0 ]]; then
            echo "Invalid JSON in coverage-final.json"
            exit 1
          fi

      # Step 8: Upload coverage reports to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Add this secret to your repo for Codecov integration
          files: ./apperals-frontend/coverage/coverage-final.json
          flags: unittests
          name: codecov-coverage

      # Step 9: Enforce Coverage Thresholds
      - name: Enforce Coverage Thresholds
        run: |
          COVERAGE=$(jq '[ . | select(.statements)] | map(.statements.pct) | add / length' ./apperals-frontend/coverage/coverage-final.json)
          REQUIRED_COVERAGE=80
          COVERAGE_ROUNDED=$(echo "$COVERAGE" | awk '{printf "%.2f", $1}')
          echo "Current Coverage: $COVERAGE_ROUNDED%"

          if (( $(echo "$COVERAGE < $REQUIRED_COVERAGE" | bc -l) )); then
            echo "Coverage is below the required $REQUIRED_COVERAGE%"
            exit 1
          fi

      # Step 10: Upload coverage reports as artifacts (optional)
      - name: Upload Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: ./apperals-frontend/coverage/
